package com.mybatis.pojo;

public class UserPrivileges {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PRIVILEGES.GRANTEE
     *
     * @mbggenerated Mon Jan 13 22:15:29 CST 2020
     */
    private String grantee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PRIVILEGES.TABLE_CATALOG
     *
     * @mbggenerated Mon Jan 13 22:15:29 CST 2020
     */
    private String tableCatalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PRIVILEGES.PRIVILEGE_TYPE
     *
     * @mbggenerated Mon Jan 13 22:15:29 CST 2020
     */
    private String privilegeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PRIVILEGES.IS_GRANTABLE
     *
     * @mbggenerated Mon Jan 13 22:15:29 CST 2020
     */
    private String isGrantable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PRIVILEGES.GRANTEE
     *
     * @return the value of USER_PRIVILEGES.GRANTEE
     *
     * @mbggenerated Mon Jan 13 22:15:29 CST 2020
     */
    public String getGrantee() {
        return grantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PRIVILEGES.GRANTEE
     *
     * @param grantee the value for USER_PRIVILEGES.GRANTEE
     *
     * @mbggenerated Mon Jan 13 22:15:29 CST 2020
     */
    public void setGrantee(String grantee) {
        this.grantee = grantee == null ? null : grantee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PRIVILEGES.TABLE_CATALOG
     *
     * @return the value of USER_PRIVILEGES.TABLE_CATALOG
     *
     * @mbggenerated Mon Jan 13 22:15:29 CST 2020
     */
    public String getTableCatalog() {
        return tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PRIVILEGES.TABLE_CATALOG
     *
     * @param tableCatalog the value for USER_PRIVILEGES.TABLE_CATALOG
     *
     * @mbggenerated Mon Jan 13 22:15:29 CST 2020
     */
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog == null ? null : tableCatalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PRIVILEGES.PRIVILEGE_TYPE
     *
     * @return the value of USER_PRIVILEGES.PRIVILEGE_TYPE
     *
     * @mbggenerated Mon Jan 13 22:15:29 CST 2020
     */
    public String getPrivilegeType() {
        return privilegeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PRIVILEGES.PRIVILEGE_TYPE
     *
     * @param privilegeType the value for USER_PRIVILEGES.PRIVILEGE_TYPE
     *
     * @mbggenerated Mon Jan 13 22:15:29 CST 2020
     */
    public void setPrivilegeType(String privilegeType) {
        this.privilegeType = privilegeType == null ? null : privilegeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PRIVILEGES.IS_GRANTABLE
     *
     * @return the value of USER_PRIVILEGES.IS_GRANTABLE
     *
     * @mbggenerated Mon Jan 13 22:15:29 CST 2020
     */
    public String getIsGrantable() {
        return isGrantable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PRIVILEGES.IS_GRANTABLE
     *
     * @param isGrantable the value for USER_PRIVILEGES.IS_GRANTABLE
     *
     * @mbggenerated Mon Jan 13 22:15:29 CST 2020
     */
    public void setIsGrantable(String isGrantable) {
        this.isGrantable = isGrantable == null ? null : isGrantable.trim();
    }
}